CREATE OR REPLACE VIEW VW_FINANCIAL_ANALYSIS AS
SELECT c.COMPANY_ID, c.COMPANY_NAME, fp.FISCAL_YEAR, fp.STATEMENT_SCOPE,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='CURRENT_ASSETS' THEN fv.VALUE_NUMBER END) AS CURRENT_ASSETS,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='CURRENT_LIABILITIES' THEN fv.VALUE_NUMBER END) AS CURRENT_LIABILITIES,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='CASH' THEN fv.VALUE_NUMBER END) AS CASH,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='INVENTORY' THEN fv.VALUE_NUMBER END) AS INVENTORY,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='REVENUE' THEN fv.VALUE_NUMBER END) AS REVENUE,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='NET_PROFIT' THEN fv.VALUE_NUMBER END) AS NET_PROFIT,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='TOTAL_ASSETS' THEN fv.VALUE_NUMBER END) AS TOTAL_ASSETS,
MAX(CASE WHEN fi.STANDARD_ITEM_CODE='EQUITY' THEN fv.VALUE_NUMBER END) AS EQUITY
FROM COMPANY c JOIN FINANCIAL_PERIOD fp ON fp.COMPANY_ID=c.COMPANY_ID JOIN FINANCIAL_VALUE fv ON fv.PERIOD_ID=fp.PERIOD_ID JOIN FINANCIAL_ITEM fi ON fi.ITEM_ID=fv.ITEM_ID
GROUP BY c.COMPANY_ID,c.COMPANY_NAME,fp.FISCAL_YEAR,fp.STATEMENT_SCOPE;
