CREATE OR REPLACE PROCEDURE CALCULATE_LIQUIDITY_RATIOS (p_period_id IN NUMBER) AS
    v_ca NUMBER;
    v_cl NUMBER;
    v_inventory NUMBER;
BEGIN
    SELECT MAX(CASE WHEN fi.STANDARD_ITEM_CODE='CURRENT_ASSETS' THEN fv.VALUE_NUMBER END),
           MAX(CASE WHEN fi.STANDARD_ITEM_CODE='CURRENT_LIABILITIES' THEN fv.VALUE_NUMBER END),
           MAX(CASE WHEN fi.STANDARD_ITEM_CODE='INVENTORY' THEN fv.VALUE_NUMBER END)
    INTO v_ca, v_cl, v_inventory
    FROM FINANCIAL_VALUE fv
    JOIN FINANCIAL_ITEM fi ON fi.ITEM_ID=fv.ITEM_ID
    WHERE fv.PERIOD_ID=p_period_id;

    IF v_cl IS NOT NULL AND v_cl <> 0 THEN
        INSERT INTO FINANCIAL_RATIO(PERIOD_ID,RATIO_CODE,RATIO_VALUE) VALUES(p_period_id,'CURRENT_RATIO',v_ca/v_cl);
        INSERT INTO FINANCIAL_RATIO(PERIOD_ID,RATIO_CODE,RATIO_VALUE) VALUES(p_period_id,'QUICK_RATIO',(v_ca-NVL(v_inventory,0))/v_cl);
    END IF;
    COMMIT;
END;
/
