CREATE OR REPLACE TRIGGER TRG_AUDIT_FINANCIAL_VALUE
AFTER INSERT OR UPDATE OR DELETE ON FINANCIAL_VALUE
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG(TABLE_NAME,OPERATION,RECORD_ID)
    VALUES('FINANCIAL_VALUE',
           CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' WHEN DELETING THEN 'DELETE' END,
           TO_CHAR(NVL(:NEW.VALUE_ID,:OLD.VALUE_ID)));
END;
/
