CREATE INDEX IDX_FV_PERIOD_ITEM ON FINANCIAL_VALUE(PERIOD_ID,ITEM_ID);
CREATE INDEX IDX_RFD_COMPANY_YEAR ON RAW_FINANCIAL_DATA(COMPANY_ID,FINANCIAL_YEAR);
CREATE INDEX IDX_ANOMALY_PERIOD_METRIC ON ANOMALY(PERIOD_ID,METRIC_CODE);
CREATE INDEX IDX_RAG_DOCUMENT_PAGE ON RAG_EVIDENCE(DOCUMENT_ID,SOURCE_PAGE);
