INSERT INTO COMPANY(COMPANY_NAME,SYMBOL,INDUSTRY) VALUES('Tata Consultancy Services','TCS','Information Technology');
INSERT INTO COMPANY(COMPANY_NAME,SYMBOL,INDUSTRY) VALUES('Tata Motors','TATAMOTORS','Automobile');
INSERT INTO COMPANY(COMPANY_NAME,SYMBOL,INDUSTRY) VALUES('Hindustan Unilever','HINDUNILVR','FMCG');
COMMIT;
